export const FETCH_GOOGLE_TRENDS = 'FETCH_GOOGLE_TRENDS';

// STOCK DATA
export const STOCK_DATA_REQUESTED = 'STOCK_DATA_REQUESTED';
export const STOCK_DATA_INVALID = 'STOCK_DATA_INVALID';
export const STOCK_DATA_SUCCESS = 'STOCK_DATA_RECEIVED';
export const STOCK_DATA_FAILED = 'STOCK_DATA_FAILED';

export const STOCK_SET_TICKER = 'STOCK_SET_TICKER';
