// STOCK DATA
export const STOCK_DATA_REQUESTED = 'STOCK_DATA_REQUESTED';
export const STOCK_DATA_INVALID = 'STOCK_DATA_INVALID';
export const STOCK_DATA_SUCCESS = 'STOCK_DATA_RECEIVED';
export const STOCK_DATA_FAILED = 'STOCK_DATA_FAILED';

export const STOCK_SET_TICKER = 'STOCK_SET_TICKER';

// GOOGLE TRENDS
export const GTRENDS_DATA_REQUESTED = 'GTRENDS_DATA_REQUESTED';
export const GTRENDS_DATA_SUCCESS = 'GTRENDS_DATA_SUCCESS';
export const GTRENDS_DATA_INVALID = 'GTRENDS_DATA_INVALID';
export const GTRENDS_DATA_FAILED = 'GTRENDS_DATA_FAILED';

export const GTRENDS_SET_TREND = 'GTRENDS_SET_TREND';
